SFUSA/force-app/main/default/objects/Barrel__c/fields/Barrel_Number__c.field-meta.xml
<CustomField>
        <fullName>Barrel_Number__c</fullName>
        <label>Barrel Number</label>
        <length>20</length>
        <type>Text</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Barrel__c/fields/Brand__c.field-meta.xml
<CustomField>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cruzan</fullName>
                </value>
                <value>
                    <fullName>El Tesoro</fullName>
                </value>
                <value>
                    <fullName>Jim Beam</fullName>
                </value>
                <value>
                    <fullName>Knob Creek</fullName>
                </value>
                <value>
                    <fullName>Makers Mark</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

SFUSA/force-app/main/default/objects/Barrel__c/fields/Case__c.field-meta.xml
<CustomField>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Barrels</relationshipLabel>
        <relationshipName>Barrels</relationshipName>
        <type>Lookup</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Barrel__c/fields/Product_Type__c.field-meta.xml
<CustomField>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brand__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Type</valueSetName>
        </valueSet>
    </CustomField>

SFUSA/force-app/main/default/objects/Barrel__c/fields/Sample_Kit__c.field-meta.xml
<CustomField>
        <fullName>Sample_Kit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sample Kit</label>
        <referenceTo>Sample_Kit__c</referenceTo>
        <relationshipLabel>Barrels</relationshipLabel>
        <relationshipName>Barrels</relationshipName>
        <type>Lookup</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Barrel__c/fields/Tier__c.field-meta.xml
<CustomField>
        <fullName>Tier__c</fullName>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tier</valueSetName>
        </valueSet>
    </CustomField>

SFUSA/force-app/main/default/objects/Barrel__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
        <fullName>Tracking_Number__c</fullName>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Barrel_Number__c/fields/Brand__c.field-meta.xml
<CustomField>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Knob Creek</fullName>
                </value>
                <value>
                    <fullName>El Tesoro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

SFUSA/force-app/main/default/objects/Barrel_Number__c/fields/Product_Type__c.field-meta.xml
<CustomField>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Type</valueSetName>
        </valueSet>
    </CustomField>

SFUSA/force-app/main/default/objects/Case/fields/Barrel__c.field-meta.xml
<CustomField>
        <fullName>Barrel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Barrel</label>
        <referenceTo>Barrel__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Case/fields/Barrel_Number__c.field-meta.xml
<CustomField>
        <fullName>Barrel_Number__c</fullName>
        <label>Barrel Number</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Case/fields/Barrel_Order_Group__c.field-meta.xml
<CustomField>
        <fullName>Barrel_Order_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Barrel Order Group</label>
        <referenceTo>Barrel_Order_Group__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
        <fullName>Brand__c</fullName>
        <description>The brand that is used in the Brand Registration process.</description>
        <inlineHelpText>Brand that is being registered</inlineHelpText>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>(ri)1</fullName>
                </value>
                <value>
                    <fullName>100 Anos</fullName>
                </value>
                <value>
                    <fullName>2 Gingers</fullName>
                </value>
                <value>
                    <fullName>Aftershock</fullName>
                </value>
                <value>
                    <fullName>Alberta Premium</fullName>
                </value>
                <value>
                    <fullName>Alberta Pure</fullName>
                </value>
                <value>
                    <fullName>Alberta Rye</fullName>
                </value>
                <value>
                    <fullName>Alberta Springs</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>Ardmore</fullName>
                </value>
                <value>
                    <fullName>Auchentoshan</fullName>
                </value>
                <value>
                    <fullName>Baker's</fullName>
                </value>
                <value>
                    <fullName>Banff Ice</fullName>
                </value>
                <value>
                    <fullName>Banff Summit</fullName>
                </value>
                <value>
                    <fullName>Basil Hayden's</fullName>
                </value>
                <value>
                    <fullName>Beam Suntory Corporate</fullName>
                </value>
                <value>
                    <fullName>Booker's</fullName>
                </value>
                <value>
                    <fullName>Bowmore</fullName>
                </value>
                <value>
                    <fullName>Bruxo</fullName>
                </value>
                <value>
                    <fullName>Calico Jack</fullName>
                </value>
                <value>
                    <fullName>Canadian Club</fullName>
                </value>
                <value>
                    <fullName>Canadian Club RTD</fullName>
                </value>
                <value>
                    <fullName>Castellana</fullName>
                </value>
                <value>
                    <fullName>CHITA</fullName>
                    <label>Chita</label>
                </value>
                <value>
                    <fullName>Conch</fullName>
                </value>
                <value>
                    <fullName>Connemara</fullName>
                </value>
                <value>
                    <fullName>Courvoisier</fullName>
                </value>
                <value>
                    <fullName>Cruzan</fullName>
                </value>
                <value>
                    <fullName>DeKuyper</fullName>
                </value>
                <value>
                    <fullName>DYC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

SFUSA/force-app/main/default/objects/Case/fields/Product_Type__c.field-meta.xml
<CustomField>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brand__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Type</valueSetName>
        </valueSet>
    </CustomField>

SFUSA/force-app/main/default/objects/Sample__c/fields/Barrel__c.field-meta.xml
<CustomField>
        <fullName>Barrel__c</fullName>
        <label>Barrel</label>
        <referenceTo>Barrel__c</referenceTo>
        <relationshipLabel>Samples</relationshipLabel>
        <relationshipName>Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Sample__c/fields/Case__c.field-meta.xml
<CustomField>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Samples</relationshipLabel>
        <relationshipName>Samples</relationshipName>
        <type>Lookup</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Sample__c/fields/Sample_Kit__c.field-meta.xml
<CustomField>
        <fullName>Sample_Kit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sample Kit</label>
        <referenceTo>Sample_Kit__c</referenceTo>
        <relationshipLabel>Samples</relationshipLabel>
        <relationshipName>Samples</relationshipName>
        <type>Lookup</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Sample__c/fields/Sample_Selected__c.field-meta.xml
<CustomField>
        <fullName>Sample_Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sample Selected</label>
        <type>Checkbox</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Sample_Kit__c/fields/Barrel_Order_Group__c.field-meta.xml
<CustomField>
        <fullName>Barrel_Order_Group__c</fullName>
        <label>Barrel Order Group</label>
        <referenceTo>Barrel_Order_Group__c</referenceTo>
        <relationshipLabel>Sample Kits</relationshipLabel>
        <relationshipName>Sample_Kits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Sample_Kit__c/fields/Case__c.field-meta.xml
<CustomField>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Sample Kits</relationshipLabel>
        <relationshipName>Sample_Kits</relationshipName>
        <type>Lookup</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Sample_Kit__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Status__c</fullName>
        <label>Delivery Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>In Transit</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

SFUSA/force-app/main/default/objects/Sample_Kit__c/fields/Sample_Selected__c.field-meta.xml
<CustomField>
        <fullName>Sample_Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sample Selected</label>
        <type>Checkbox</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Sample_Kit__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
        <fullName>Tracking_Number__c</fullName>
        <externalId>true</externalId>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

SFUSA/force-app/main/default/objects/Sample_Kit__c/fields/Tracking_Number_Creation_Date__c.field-meta.xml
<CustomField>
        <fullName>Tracking_Number_Creation_Date__c</fullName>
        <label>Kit Delivery Date</label>
        <type>DateTime</type>
    </CustomField>

SFUSA/force-app/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>10 YEAR SINGLE MALT</fullName>
    </customValue>
    <customValue>
        <fullName>12 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>15 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>15 YEAR SINGLE MALT</fullName>
    </customValue>
    <customValue>
        <fullName>17 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>18 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>18 YEAR SINGLE MALT</fullName>
    </customValue>
    <customValue>
        <fullName>1961 50 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>1965</fullName>
    </customValue>
    <customValue>
        <fullName>1988</fullName>
    </customValue>
    <customValue>
        <fullName>21 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>23 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>25TH ANNIVERSARY</fullName>
    </customValue>
    <customValue>
        <fullName>25 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>27 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>28 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>30 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>3 WOOD</fullName>
    </customValue>
    <customValue>
        <fullName>3 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>46</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>ADDITIONAL NOTES</fullName>
    </customValue>
    <customValue>
        <fullName>AGUA FUERTE</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN OAK</fullName>
    </customValue>
    <customValue>
        <fullName>ANEJO</fullName>
    </customValue>
    <customValue>
        <fullName>ANEJO CRISTALINO</fullName>
    </customValue>
    <customValue>
        <fullName>APPLE</fullName>
    </customValue>
    <customValue>
        <fullName>BARENAKED VODKA</fullName>
    </customValue>
    <customValue>
        <fullName>BARTENDER&apos;S MALT</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

SFUSA/force-app/main/default/classes/SBP_SampleKitRelatedListController.cls
public class SBP_SampleKitRelatedListController {
    @AuraEnabled
    public static list<Sample_Kit__c> getAllSampleKits(string CaseRecId)
    {
        system.debug('CaseRecId'+CaseRecId);
        List<Sample_Kit__c> kitList=new List<Sample_Kit__c>();
        //List<contact> conListToReturn=new List<contact>();
        for(Sample_Kit__c obj:[Select id,Name,Sample_Selected__c,Tracking_Number_Creation_Date__c,Barrel_Order_Group__c,Delivery_Status__c,Tracking_Number__c,Case__c from Sample_Kit__c where Case__c=:CaseRecId  ORDER BY CreatedDate DESC LIMIT 1000])
        {
            kitList.add(obj);
        }
        
        return kitList;
    }
    @AuraEnabled
    public static Case getCaseDetails(string CaseRecId ){
        Case caserec = new Case();
        caserec = [SELECT id,CaseNumber,Barrel_Order_Group__c,Brand__c from Case where id=:CaseRecId];
        
        return caserec;
    }
    @AuraEnabled
    public static Boolean DeleteSampleKitRecord(string samplekitdelId){
        Sample_kit__c samplekit = new Sample_Kit__c();
        samplekit= [SELECT ID FROM Sample_Kit__c WHERE ID=:samplekitdelId];
        if(samplekit!=null){
            delete samplekit;
            return true;
        }
        return false;
    }
    
    @AuraEnabled
    public static Boolean create3Samples(string samplekitId){
        System.debug('inside create3Samples:::'+samplekitId);
        Id SamplekitCaseId;
        List<Barrel__c> barrelList = new List<Barrel__c>();
        List<Sample_Kit__c> sampleKitList = [Select id,Name,Case__c, Case__r.Brand__c, Case__r.Product_Type__c, Case__r.Barrel__r.Barrel_Number__c from Sample_Kit__c where Id=:samplekitId LIMIT 1];
        
        
        for(Sample_Kit__c obj : sampleKitList)
        {
            if(samplekitId!=null){
                
                SamplekitCaseId = obj.Case__c;
                
                for(Integer i=0;i<=2;i++){
                    Barrel__c barrel = new Barrel__c();
                    barrel.Brand__c = obj.Case__r.Brand__c;
                    barrel.RecordTypeId = SBP_Constants.KNOB_CREEK_SAMPLE_KIT_RT_ID;    
                    barrel.Product_Type__c = obj.Case__r.Product_Type__c;
                    barrel.Tier__c = '1';
                    barrelList.add(barrel);
                }
                
                insert barrelList;
                
                for(Integer j=0;j<barrelList.size();j++){
                    Sample__c sample = new Sample__c();
                    sample.Barrel__c = barrelList[j].Id;
                    sample.Sample_Kit__c = samplekitId;
                    sample.SampleId__c = obj.Case__r.Barrel__r.Barrel_Number__c;    
                    insert sample;
                }
                
            }
        }
        
        List<Sample__c> sampleList = [select Label__c, Sample_Kit__c from Sample__c where Sample_Kit__c=:samplekitId];
        List<Barrel__c> barrelListNew = [select Id, Barrel_Number__c, Case__c from Barrel__c where Case__c=:SamplekitCaseId];
        
        if(sampleList.size()>0){
            for(Integer k=0;k<sampleList.size();k++){
                if(barrelListNew.size()>0){
                    for(Barrel__c b: barrelListNew){
                        sampleList[0].SampleId__c = b.Barrel_Number__c + 'A';
                        sampleList[0].Label__c = 'A';
                        sampleList[1].SampleId__c = b.Barrel_Number__c + 'B';
                        sampleList[1].Label__c = 'B';
                        sampleList[2].SampleId__c = b.Barrel_Number__c + 'C';
                        sampleList[2].Label__c = 'C';
                    }
                }
            }
            update sampleList;
            return true;
        }
        
        return false;
    }
}